/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the cycas SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx categoriesCreate.example.ts
 */

import { Cycas } from "cycas";

const cycas = new Cycas();

async function main() {
  const result = await cycas.categories.create({
    name: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
