/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateCategoryRequest = {
  name: string;
};

/**
 * Category created
 */
export type CreateCategoryResponse = {
  name: string;
  id: string;
};

/** @internal */
export type CreateCategoryRequest$Outbound = {
  name: string;
};

/** @internal */
export const CreateCategoryRequest$outboundSchema: z.ZodMiniType<
  CreateCategoryRequest$Outbound,
  CreateCategoryRequest
> = z.object({
  name: z.string(),
});

export function createCategoryRequestToJSON(
  createCategoryRequest: CreateCategoryRequest,
): string {
  return JSON.stringify(
    CreateCategoryRequest$outboundSchema.parse(createCategoryRequest),
  );
}

/** @internal */
export const CreateCategoryResponse$inboundSchema: z.ZodMiniType<
  CreateCategoryResponse,
  unknown
> = z.object({
  name: types.string(),
  id: types.string(),
});

export function createCategoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCategoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCategoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCategoryResponse' from JSON`,
  );
}
