DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app') THEN
    CREATE ROLE app
        LOGIN
        PASSWORD '…';
  END IF;
END$$;

GRANT CONNECT ON DATABASE postgres TO app;
GRANT USAGE ON SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
