/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesCreate } from "../funcs/categoriesCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Categories extends ClientSDK {
  async create(
    request: operations.CreateCategoryRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCategoryResponse> {
    return unwrapAsync(categoriesCreate(
      this,
      request,
      options,
    ));
  }
}
