/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Categories } from "./categories.js";

export class Cycas extends ClientSDK {
  private _categories?: Categories;
  get categories(): Categories {
    return (this._categories ??= new Categories(this._options));
  }
}
