workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Cycas API:
        inputs:
            - location: ../api/spec/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/bashr/cycas-workspace/cycas-api
targets:
    cycas:
        target: typescript
        source: Cycas API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bashr/cycas-workspace/cycas-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
